export type PokemonType =
  | "normal"
  | "fire"
  | "water"
  | "electric"
  | "grass"
  | "ice"
  | "fighting"
  | "poison"
  | "ground"
  | "flying"
  | "psychic"
  | "bug"
  | "rock"
  | "ghost"
  | "dragon"
  | "dark"
  | "steel"
  | "fairy";

export type Pokemon = {
  id: number;
  slug: string;
  name: { he: string; en: string };
  description: { he: string; en: string };
  powers: { he: string[]; en: string[] };
  types: PokemonType[];
  chain: string[];
};

const createPokemon = (
  id: number,
  slug: string,
  heName: string,
  enName: string,
  heDescription: string,
  enDescription: string,
  hePowers: string[],
  enPowers: string[],
  types: PokemonType[],
  chain: string[],
): Pokemon => ({
  id,
  slug,
  name: { he: heName, en: enName },
  description: { he: heDescription, en: enDescription },
  powers: { he: hePowers, en: enPowers },
  types,
  chain,
});

const eeveeChain = [
  "eevee",
  "vaporeon",
  "jolteon",
  "flareon",
  "espeon",
  "umbreon",
  "leafeon",
  "glaceon",
  "sylveon",
];

export const morePokemon: Pokemon[] = [
  createPokemon(
    63,
    "abra",
    "אברה",
    "Abra",
    "פוקימון קטן וישנוני שמרגיש סכנה גם מתוך שינה ונעלם ברגע בעזרת טלפורט.",
    "A sleepy little Pokémon that senses danger even while dreaming and teleports away in a flash.",
    ["טלפורט", "בלבול", "מסך אור", "השתקפות", "כדור צל"],
    ["Teleport", "Confusion", "Light Screen", "Reflect", "Shadow Ball"],
    ["psychic"],
    ["abra", "kadabra", "alakazam"],
  ),
  createPokemon(
    64,
    "kadabra",
    "קדברה",
    "Kadabra",
    "הכפית שלו עוזרת לו לרכז כוחות על־חושיים ולכופף חפצים בלי לגעת בהם.",
    "Its spoon helps focus psychic power so it can bend objects without touching them.",
    ["בלבול", "פסייבים", "שיקום", "טלפורט", "פסיכוקאט", "מסך אור"],
    ["Confusion", "Psybeam", "Recover", "Teleport", "Psycho Cut", "Light Screen"],
    ["psychic"],
    ["abra", "kadabra", "alakazam"],
  ),
  createPokemon(
    65,
    "alakazam",
    "אלאקזם",
    "Alakazam",
    "מוחו המבריק זוכר הכול, ושתי הכפיות שלו מעצימות את הכוח העל־חושי.",
    "Its brilliant mind remembers everything, and its two spoons boost its psychic power.",
    ["פסיכי", "פסייבים", "שיקום", "ראיית עתיד", "כדור צל", "מיקוד פיצוץ"],
    ["Psychic", "Psybeam", "Recover", "Future Sight", "Shadow Ball", "Focus Blast"],
    ["psychic"],
    ["abra", "kadabra", "alakazam"],
  ),
  createPokemon(
    92,
    "gastly",
    "גאסטלי",
    "Gastly",
    "כדור גז שובב שמרחף דרך קירות ואוהב להפתיע מטיילים בלילה.",
    "A playful ball of gas that floats through walls and loves surprising nighttime travelers.",
    ["ליקוק", "קרן בלבול", "גז רעיל", "כדור צל", "קללה"],
    ["Lick", "Confuse Ray", "Poison Gas", "Shadow Ball", "Curse"],
    ["ghost", "poison"],
    ["gastly", "haunter", "gengar"],
  ),
  createPokemon(
    93,
    "haunter",
    "האנטר",
    "Haunter",
    "הידיים המרחפות שלו מתגנבות מכל כיוון, אבל הוא בעיקר נהנה ממתיחות מצחיקות.",
    "Its floating hands sneak in from every direction, though it mostly enjoys silly pranks.",
    ["כדור צל", "ליקוק", "אגרוף צל", "היפנוזה", "אוכל חלומות", "גל רעל"],
    ["Shadow Ball", "Lick", "Shadow Punch", "Hypnosis", "Dream Eater", "Venoshock"],
    ["ghost", "poison"],
    ["gastly", "haunter", "gengar"],
  ),
  createPokemon(
    94,
    "gengar",
    "גנגר",
    "Gengar",
    "פוקימון צללים עם חיוך ענק שמתחבא בפינות חשוכות וממציא מתיחות.",
    "A grinning shadow Pokémon that hides in dark corners and dreams up mischievous tricks.",
    ["כדור צל", "פצצת בוץ", "היפנוזה", "אוכל חלומות", "ברק", "כדור אנרגיה"],
    ["Shadow Ball", "Sludge Bomb", "Hypnosis", "Dream Eater", "Thunderbolt", "Energy Ball"],
    ["ghost", "poison"],
    ["gastly", "haunter", "gengar"],
  ),
  createPokemon(
    129,
    "magikarp",
    "מג׳יקארפ",
    "Magikarp",
    "דג עקשן שממשיך לקפוץ גם כשנדמה שאין לו כוח, ובסוף מצפה לו שינוי אדיר.",
    "A determined fish that keeps splashing even when it seems powerless, with an amazing change ahead.",
    ["התזה", "התנגשות", "נפילה", "הידרו פאמפ"],
    ["Splash", "Tackle", "Flail", "Hydro Pump"],
    ["water"],
    ["magikarp", "gyarados"],
  ),
  createPokemon(
    130,
    "gyarados",
    "גיארדוס",
    "Gyarados",
    "דרקון ים עצום שנולד ממג׳יקארפ קטן ומסוגל ליצור גלים אדירים.",
    "A huge sea dragon that grows from tiny Magikarp and can create towering waves.",
    ["הידרו פאמפ", "זנב מים", "נשיכת מחץ", "ריקוד דרקון", "הוריקן", "קרן קרח"],
    ["Hydro Pump", "Aqua Tail", "Crunch", "Dragon Dance", "Hurricane", "Ice Beam"],
    ["water", "flying"],
    ["magikarp", "gyarados"],
  ),
  createPokemon(
    131,
    "lapras",
    "לאפרס",
    "Lapras",
    "ענקית ים עדינה שאוהבת להסיע חברים על השריון ולשיר בקול נעים.",
    "A gentle sea giant that carries friends on its shell and sings with a beautiful voice.",
    ["גלישה", "קרן קרח", "שיר", "הידרו פאמפ", "שירת ריפוי", "סופת שלג"],
    ["Surf", "Ice Beam", "Sing", "Hydro Pump", "Heal Bell", "Blizzard"],
    ["water", "ice"],
    ["lapras"],
  ),
  createPokemon(
    132,
    "ditto",
    "דיטו",
    "Ditto",
    "פוקימון גמיש שיכול לשנות את צורתו ולהעתיק כמעט כל פוקימון שהוא רואה.",
    "A flexible Pokémon that can transform and copy almost any Pokémon it sees.",
    ["שינוי צורה"],
    ["Transform"],
    ["normal"],
    ["ditto"],
  ),
  createPokemon(
    147,
    "dratini",
    "דראטיני",
    "Dratini",
    "דרקון מים צעיר ונדיר שגדל במהירות ומשיל את עורו שוב ושוב.",
    "A rare young water dragon that grows quickly and sheds its skin again and again.",
    ["זעם דרקון", "גל רעם", "זנב מים", "טוויסטר", "זריזות"],
    ["Dragon Rage", "Thunder Wave", "Aqua Tail", "Twister", "Agility"],
    ["dragon"],
    ["dratini", "dragonair", "dragonite"],
  ),
  createPokemon(
    148,
    "dragonair",
    "דראגונאייר",
    "Dragonair",
    "דרקון אלגנטי שהכדורים הכחולים שעל גופו זוהרים כשהוא משנה את מזג האוויר.",
    "An elegant dragon whose blue orbs glow when it changes the weather.",
    ["פעימת דרקון", "זנב מים", "ריקוד גשם", "גל רעם", "אקו ג׳ט", "דרקון ראש"],
    ["Dragon Pulse", "Aqua Tail", "Rain Dance", "Thunder Wave", "Aqua Jet", "Dragon Rush"],
    ["dragon"],
    ["dratini", "dragonair", "dragonite"],
  ),
  createPokemon(
    149,
    "dragonite",
    "דרגונייט",
    "Dragonite",
    "דרקון חזק וטוב לב שטס מעל הים וממהר לעזור לספינות שאיבדו את דרכן.",
    "A powerful, kindhearted dragon that flies over the sea to help lost ships.",
    ["פעימת דרקון", "הוריקן", "רעם", "אגרוף אש", "מהירות קיצונית", "טיסה"],
    ["Dragon Pulse", "Hurricane", "Thunder", "Fire Punch", "Extreme Speed", "Fly"],
    ["dragon", "flying"],
    ["dratini", "dragonair", "dragonite"],
  ),
  createPokemon(
    150,
    "mewtwo",
    "מיוטו",
    "Mewtwo",
    "פוקימון נדיר ועוצמתי בעל כוחות מחשבה אדירים, שלומד לבחור בעצמו את דרכו.",
    "A rare and powerful Pokémon with incredible mind powers that learns to choose its own path.",
    ["פסיכי", "כדור אאורה", "שיקום", "פסייק סטרייק", "כדור צל", "קרן קרח"],
    ["Psychic", "Aura Sphere", "Recover", "Psystrike", "Shadow Ball", "Ice Beam"],
    ["psychic"],
    ["mewtwo"],
  ),
  createPokemon(
    151,
    "mew",
    "מיו",
    "Mew",
    "פוקימון מסתורי, סקרן ושובב שמרחף בשקט ויכול ללמוד מגוון עצום של כוחות.",
    "A mysterious, curious, and playful Pokémon that floats quietly and can learn an enormous variety of moves.",
    ["פסיכי", "שינוי צורה", "כדור אאורה", "כוח עתיק", "טלפורט", "מטרונום"],
    ["Psychic", "Transform", "Aura Sphere", "Ancient Power", "Teleport", "Metronome"],
    ["psychic"],
    ["mew"],
  ),
  createPokemon(
    196,
    "espeon",
    "אספיאון",
    "Espeon",
    "התפתחות על־חושית של איווי שקוראת תנועות זעירות באוויר וחוזה מה יקרה.",
    "Eevee’s psychic evolution reads tiny movements in the air and predicts what will happen.",
    ["פסיכי", "קרן בוקר", "ראיית עתיד", "כדור צל", "כוכבים מהירים"],
    ["Psychic", "Morning Sun", "Future Sight", "Shadow Ball", "Swift"],
    ["psychic"],
    eeveeChain,
  ),
  createPokemon(
    197,
    "umbreon",
    "אמבריאון",
    "Umbreon",
    "התפתחות הלילה של איווי; הטבעות שעל פרוותו זוהרות באור הירח.",
    "Eevee’s nighttime evolution has rings that glow softly in the moonlight.",
    ["פעימת חושך", "קרן ירח", "הטעיה", "נשיכת מחץ", "אור בלבול", "שמירה"],
    ["Dark Pulse", "Moonlight", "Feint Attack", "Crunch", "Confuse Ray", "Protect"],
    ["dark"],
    eeveeChain,
  ),
  createPokemon(
    470,
    "leafeon",
    "ליפיאון",
    "Leafeon",
    "התפתחות היער של איווי שממלאת את האוויר בריח עלים נקי ורענן.",
    "Eevee’s forest evolution fills the air with the clean, fresh scent of leaves.",
    ["להב עלה", "סינתזה", "עלה תער", "ריקוד חרבות", "קרן שמש"],
    ["Leaf Blade", "Synthesis", "Razor Leaf", "Swords Dance", "Solar Beam"],
    ["grass"],
    eeveeChain,
  ),
  createPokemon(
    471,
    "glaceon",
    "גלייסיאון",
    "Glaceon",
    "התפתחות הקרח של איווי שמקררת את פרוותה ויוצרת גבישי שלג נוצצים.",
    "Eevee’s ice evolution chills its fur to create sparkling snow crystals.",
    ["קרן קרח", "רוח קפואה", "סופת שלג", "רסיס קרח", "הקפאה יבשה"],
    ["Ice Beam", "Icy Wind", "Blizzard", "Ice Shard", "Freeze-Dry"],
    ["ice"],
    eeveeChain,
  ),
  createPokemon(
    700,
    "sylveon",
    "סילביאון",
    "Sylveon",
    "התפתחות הפיה של איווי משתמשת בסרטים הרכים שלה כדי להרגיע ולהגן על חברים.",
    "Eevee’s fairy evolution uses its soft ribbons to comfort and protect friends.",
    ["פיצוץ ירח", "קול מכשף", "נשיקת ניקוז", "עיניים מתוקות", "מהירות כוכב"],
    ["Moonblast", "Disarming Voice", "Draining Kiss", "Baby-Doll Eyes", "Swift"],
    ["fairy"],
    eeveeChain,
  ),
  createPokemon(
    175,
    "togepi",
    "טוגפי",
    "Togepi",
    "פוקימון תינוק ששומר רגשות שמחים בתוך הקליפה ומחלק מזל טוב לסובבים אותו.",
    "A baby Pokémon that stores happy feelings in its shell and shares good luck with everyone nearby.",
    ["מטרונום", "קסם", "נשיקה מתוקה", "כוח עתיק", "פיה רוח"],
    ["Metronome", "Charm", "Sweet Kiss", "Ancient Power", "Fairy Wind"],
    ["fairy"],
    ["togepi", "togetic", "togekiss"],
  ),
  createPokemon(
    176,
    "togetic",
    "טוגטיק",
    "Togetic",
    "הוא מופיע ליד אנשים טובי לב ומפזר סביבם אבקת אושר מנצנצת.",
    "It appears near kindhearted people and scatters sparkling happiness around them.",
    ["כוח עתיק", "פיה רוח", "משאלה", "תעופה", "קסם", "מטרונום"],
    ["Ancient Power", "Fairy Wind", "Wish", "Fly", "Charm", "Metronome"],
    ["fairy", "flying"],
    ["togepi", "togetic", "togekiss"],
  ),
  createPokemon(
    468,
    "togekiss",
    "טוגקיס",
    "Togekiss",
    "פוקימון שמביא ברכה למקומות שלווים ודואה בשמיים בכנפיים שקטות.",
    "A Pokémon that brings blessings to peaceful places and glides on silent wings.",
    ["חיתוך אווירי", "ברק מסנוור", "כדור אאורה", "משאלה", "מהירות קיצונית", "כוח עתיק"],
    ["Air Slash", "Dazzling Gleam", "Aura Sphere", "Wish", "Extreme Speed", "Ancient Power"],
    ["fairy", "flying"],
    ["togepi", "togetic", "togekiss"],
  ),
  createPokemon(
    246,
    "larvitar",
    "לארביטר",
    "Larvitar",
    "פוקימון סלע קטן שאוכל אדמה ואבנים כדי לגדול ולהתחזק.",
    "A small rock Pokémon that eats soil and stones to grow bigger and stronger.",
    ["נשיכה", "זריקת סלע", "רעידת אדמה", "חפירה", "פני פחד"],
    ["Bite", "Rock Throw", "Earthquake", "Dig", "Scary Face"],
    ["rock", "ground"],
    ["larvitar", "pupitar", "tyranitar"],
  ),
  createPokemon(
    247,
    "pupitar",
    "פופיטר",
    "Pupitar",
    "קליפתו קשה כמו סלע, ובתוכה הוא אוסף כוח לקראת ההתפתחות הבאה.",
    "Its shell is hard as stone, and inside it gathers power for its next evolution.",
    ["קבר סלע", "נשיכת מחץ", "הקשחה", "חפירה", "גלישת סלע"],
    ["Rock Tomb", "Crunch", "Harden", "Dig", "Rock Slide"],
    ["rock", "ground"],
    ["larvitar", "pupitar", "tyranitar"],
  ),
  createPokemon(
    248,
    "tyranitar",
    "טיירניטאר",
    "Tyranitar",
    "ענק משוריין שצעדיו מרעידים את הקרקע והוא מגן בנחישות על הטריטוריה שלו.",
    "An armored giant whose steps shake the ground and who fiercely protects its territory.",
    ["קצה אבן", "נשיכת מחץ", "רעידת אדמה", "פעימת חושך", "אגרוף אש", "סופת חול"],
    ["Stone Edge", "Crunch", "Earthquake", "Dark Pulse", "Fire Punch", "Sandstorm"],
    ["rock", "dark"],
    ["larvitar", "pupitar", "tyranitar"],
  ),
  createPokemon(
    252,
    "treecko",
    "טריקו",
    "Treecko",
    "שממית יער זריזה שנצמדת לקירות בעזרת כפות רגליים מיוחדות ונשארת רגועה תמיד.",
    "A quick forest gecko that grips walls with special feet and stays calm in any situation.",
    ["קליע זרעים", "מהירות", "ספיגה", "מתקפה מהירה", "רדיפה"],
    ["Bullet Seed", "Quick Attack", "Absorb", "Swift", "Pursuit"],
    ["grass"],
    ["treecko", "grovyle", "sceptile"],
  ),
  createPokemon(
    253,
    "grovyle",
    "גרובייל",
    "Grovyle",
    "מטפס מומחה שמדלג בין ענפים במהירות והעלים שעל זרועותיו חדים כלהבים.",
    "An expert climber that leaps between branches, with leaves on its arms as sharp as blades.",
    ["להב עלה", "מתקפה מהירה", "זיהוי", "קליע זרעים", "זעם"],
    ["Leaf Blade", "Quick Attack", "Detect", "Bullet Seed", "Fury Cutter"],
    ["grass"],
    ["treecko", "grovyle", "sceptile"],
  ),
  createPokemon(
    254,
    "sceptile",
    "ספטייל",
    "Sceptile",
    "שומר יער מהיר שמטפח עצים באהבה ונלחם בעזרת עלים חדים.",
    "A speedy forest guardian that cares for trees and battles with razor-sharp leaves.",
    ["להב עלה", "סערת עלים", "פעימת דרקון", "רעידת אדמה", "קליע זרעים", "מתקפה מהירה"],
    ["Leaf Blade", "Leaf Storm", "Dragon Pulse", "Earthquake", "Bullet Seed", "Quick Attack"],
    ["grass"],
    ["treecko", "grovyle", "sceptile"],
  ),
  createPokemon(
    255,
    "torchic",
    "טורצ׳יק",
    "Torchic",
    "אפרוח חמים שהאש בבטנו שומרת עליו נעים ומאירה את הדרך בחושך.",
    "A warm little chick whose inner flame keeps it cozy and lights the way in darkness.",
    ["גחלת", "ניקור", "מיקוד אנרגיה", "התקפת חול", "להבה"],
    ["Ember", "Peck", "Focus Energy", "Sand Attack", "Flame Charge"],
    ["fire"],
    ["torchic", "combusken", "blaziken"],
  ),
  createPokemon(
    256,
    "combusken",
    "קומבסקן",
    "Combusken",
    "לוחם נמרץ שמאמן את הרגליים בכל יום ומשלב בעיטות מהירות עם אש.",
    "An energetic fighter that trains its legs every day and combines fast kicks with fire.",
    ["בעיטה כפולה", "ניקור", "להבה", "גחלת", "חיתוך"],
    ["Double Kick", "Peck", "Flame Charge", "Ember", "Slash"],
    ["fire", "fighting"],
    ["torchic", "combusken", "blaziken"],
  ),
  createPokemon(
    257,
    "blaziken",
    "בלייזיקן",
    "Blaziken",
    "לוחם אש מהיר שמזנק גבוה ומדליק להבות סביב אגרופיו ורגליו.",
    "A swift fire fighter that leaps high and wraps its fists and feet in flame.",
    ["בעיטת להבה", "בעיטת שמיים", "אגרוף אש", "להביור", "התמקדות", "ציפור אמיצה"],
    ["Blaze Kick", "High Jump Kick", "Fire Punch", "Flamethrower", "Focus Blast", "Brave Bird"],
    ["fire", "fighting"],
    ["torchic", "combusken", "blaziken"],
  ),
  createPokemon(
    258,
    "mudkip",
    "מאדקיפ",
    "Mudkip",
    "הסנפיר שעל ראשו מרגיש תנועות במים ובאוויר ועוזר לו למצוא את הדרך.",
    "The fin on its head senses movement in water and air, helping it find its way.",
    ["אקדח מים", "התנגשות", "זריקת בוץ", "נהמה", "סילון מים"],
    ["Water Gun", "Tackle", "Mud-Slap", "Growl", "Aqua Jet"],
    ["water"],
    ["mudkip", "marshtomp", "swampert"],
  ),
  createPokemon(
    259,
    "marshtomp",
    "מארשטומפ",
    "Marshtomp",
    "הוא נע בקלות בבוץ ומפתח רגליים חזקות שמאפשרות לו לדחוף סלעים.",
    "It moves easily through mud and has powerful legs that can push large rocks.",
    ["יריית בוץ", "פעימת מים", "חפירה", "מפולת סלעים", "התנגשות"],
    ["Mud Shot", "Water Pulse", "Dig", "Rock Slide", "Tackle"],
    ["water", "ground"],
    ["mudkip", "marshtomp", "swampert"],
  ),
  createPokemon(
    260,
    "swampert",
    "סוואמפרט",
    "Swampert",
    "פוקימון חזק ששוחה מהר, מרגיש סערות מתקרבות ומגן על ביתו ליד המים.",
    "A powerful swimmer that senses approaching storms and protects its waterside home.",
    ["רעידת אדמה", "הידרו פאמפ", "זרוע פטיש", "גלישה", "מפולת סלעים", "מי בוץ"],
    ["Earthquake", "Hydro Pump", "Hammer Arm", "Surf", "Rock Slide", "Muddy Water"],
    ["water", "ground"],
    ["mudkip", "marshtomp", "swampert"],
  ),
  createPokemon(
    280,
    "ralts",
    "ראלטס",
    "Ralts",
    "הקרניים שעל ראשו מרגישות רגשות, והוא מתקרב בשמחה לאנשים רגועים וטובים.",
    "The horns on its head sense emotions, and it happily approaches calm, kind people.",
    ["בלבול", "קול מכשף", "טלפורט", "חיים טלפתיים", "נשיקת ניקוז"],
    ["Confusion", "Disarming Voice", "Teleport", "Life Dew", "Draining Kiss"],
    ["psychic", "fairy"],
    ["ralts", "kirlia", "gardevoir", "gallade"],
  ),
  createPokemon(
    281,
    "kirlia",
    "קירליה",
    "Kirlia",
    "הוא רוקד כשמאמנו שמח ומשתמש בכוחותיו כדי ליצור תמונות יפות באוויר.",
    "It dances when its Trainer is happy and uses psychic power to create beautiful visions.",
    ["בלבול", "פסייבים", "נשיקת ניקוז", "ריקוד קסום", "טלפורט"],
    ["Confusion", "Psybeam", "Draining Kiss", "Magical Leaf", "Teleport"],
    ["psychic", "fairy"],
    ["ralts", "kirlia", "gardevoir", "gallade"],
  ),
  createPokemon(
    282,
    "gardevoir",
    "גרדבואר",
    "Gardevoir",
    "פוקימון נאמן שקורא רגשות ויוצר מחסום על־חושי חזק כדי להגן על חבריו.",
    "A loyal Pokémon that reads feelings and creates powerful psychic barriers to protect friends.",
    ["פסיכי", "פיצוץ ירח", "כדור צל", "נשיקת ניקוז", "ראיית עתיד", "ריפוי משאלה"],
    ["Psychic", "Moonblast", "Shadow Ball", "Draining Kiss", "Future Sight", "Healing Wish"],
    ["psychic", "fairy"],
    ["ralts", "kirlia", "gardevoir", "gallade"],
  ),
  createPokemon(
    475,
    "gallade",
    "גאלייד",
    "Gallade",
    "לוחם אבירי שמרגיש סכנה מראש ומגן על אחרים בלהבים שבזרועותיו.",
    "A knightly fighter that senses danger early and protects others with the blades on its arms.",
    ["פסיכוקאט", "קרב צמוד", "להב עלה", "חיתוך לילה", "ריקוד חרבות", "זינוק"],
    ["Psycho Cut", "Close Combat", "Leaf Blade", "Night Slash", "Swords Dance", "Feint"],
    ["psychic", "fighting"],
    ["ralts", "kirlia", "gardevoir", "gallade"],
  ),
  createPokemon(
    374,
    "beldum",
    "בלדאם",
    "Beldum",
    "פוקימון מתכת שמרחף בעזרת מגנטיות ומתקשר עם חבריו בגלים מיוחדים.",
    "A metal Pokémon that floats with magnetism and communicates using special waves.",
    ["התנגשות", "ראש ברזל", "ראש זן", "הגנת ברזל"],
    ["Tackle", "Iron Head", "Zen Headbutt", "Iron Defense"],
    ["steel", "psychic"],
    ["beldum", "metang", "metagross"],
  ),
  createPokemon(
    375,
    "metang",
    "מטאנג",
    "Metang",
    "שני בלדאם מתחברים לגוף חזק עם מוח מהיר וטפרי מתכת עוצמתיים.",
    "Two Beldum join into a strong body with a quick mind and powerful metal claws.",
    ["טופר מתכת", "ראש זן", "פסיכי", "מרדף", "הגנת ברזל"],
    ["Metal Claw", "Zen Headbutt", "Psychic", "Pursuit", "Iron Defense"],
    ["steel", "psychic"],
    ["beldum", "metang", "metagross"],
  ),
  createPokemon(
    376,
    "metagross",
    "מטאגרוס",
    "Metagross",
    "מחשב־על מהלך בעל ארבע רגליים שמנתח מצבים במהירות ומרים משקל עצום.",
    "A four-legged walking supercomputer that analyzes situations quickly and lifts enormous weight.",
    ["מחץ מטאור", "פסיכי", "רעידת אדמה", "זרוע פטיש", "ראש זן", "תותח הבזק"],
    ["Meteor Mash", "Psychic", "Earthquake", "Hammer Arm", "Zen Headbutt", "Flash Cannon"],
    ["steel", "psychic"],
    ["beldum", "metang", "metagross"],
  ),
  createPokemon(
    403,
    "shinx",
    "שינקס",
    "Shinx",
    "גור חשמלי שהפרווה שלו זוהרת כשהוא אוסף חשמל בשרירים.",
    "An electric cub whose fur glows when it gathers electricity in its muscles.",
    ["ניצוץ", "התנגשות", "נהמה", "נשיכה", "גל רעם"],
    ["Spark", "Tackle", "Leer", "Bite", "Thunder Wave"],
    ["electric"],
    ["shinx", "luxio", "luxray"],
  ),
  createPokemon(
    404,
    "luxio",
    "לוקסיו",
    "Luxio",
    "הטפרים שלו מעבירים חשמל, והוא מתקשר עם חברי הלהקה בעזרת זנבו הזוהר.",
    "Its claws carry electricity, and it signals its pack using its glowing tail.",
    ["ניצוץ", "נשיכה", "גל רעם", "מתקפה מהירה", "ניב רעם"],
    ["Spark", "Bite", "Thunder Wave", "Quick Attack", "Thunder Fang"],
    ["electric"],
    ["shinx", "luxio", "luxray"],
  ),
  createPokemon(
    405,
    "luxray",
    "לוקסריי",
    "Luxray",
    "עיניו המיוחדות רואות דרך מכשולים ועוזרות לו למצוא חברים שאבדו.",
    "Its special eyes see through obstacles and help it find lost friends.",
    ["הסתערות פראית", "ניב רעם", "נשיכת מחץ", "וולט סוויץ׳", "עיניים חשמליות", "גל רעם"],
    ["Wild Charge", "Thunder Fang", "Crunch", "Volt Switch", "Electric Terrain", "Thunder Wave"],
    ["electric"],
    ["shinx", "luxio", "luxray"],
  ),
  createPokemon(
    443,
    "gible",
    "גיבל",
    "Gible",
    "דרקון קטן שאוהב להתחפר במערות חמות ולנשוך כל דבר מסקרן.",
    "A small dragon that burrows in warm caves and nibbles anything interesting.",
    ["נשיכה", "חפירה", "זעם דרקון", "התקפת חול", "חיתוך"],
    ["Bite", "Dig", "Dragon Rage", "Sand Attack", "Slash"],
    ["dragon", "ground"],
    ["gible", "gabite", "garchomp"],
  ),
  createPokemon(
    444,
    "gabite",
    "גאבייט",
    "Gabite",
    "הוא אוסף אבנים נוצצות במערה שלו וטס למרחקים קצרים בעזרת סנפיריו.",
    "It collects shiny stones in its cave and glides short distances using its fins.",
    ["טופר דרקון", "חפירה", "חיתוך", "קבר חול", "דרקון ראש"],
    ["Dragon Claw", "Dig", "Slash", "Sand Tomb", "Dragon Rush"],
    ["dragon", "ground"],
    ["gible", "gabite", "garchomp"],
  ),
  createPokemon(
    445,
    "garchomp",
    "גארצ׳ומפ",
    "Garchomp",
    "דרקון מהיר כברק שדוהר באוויר כמו מטוס ושומר על מערתו.",
    "A lightning-fast dragon that races through the air like a jet and guards its cave.",
    ["טופר דרקון", "רעידת אדמה", "דרקון ראש", "קצה אבן", "חפירה", "ניב אש"],
    ["Dragon Claw", "Earthquake", "Dragon Rush", "Stone Edge", "Dig", "Fire Fang"],
    ["dragon", "ground"],
    ["gible", "gabite", "garchomp"],
  ),
  createPokemon(
    447,
    "riolu",
    "ריולו",
    "Riolu",
    "גור לוחם שמרגיש את האנרגיה של יצורים אחרים ומתאמן בהתמדה.",
    "A young fighter that senses the energy of others and trains with determination.",
    ["מתקפה מהירה", "כוח דקל", "התקפת נגד", "צעקה", "חיקוי"],
    ["Quick Attack", "Force Palm", "Counter", "Screech", "Copycat"],
    ["fighting"],
    ["riolu", "lucario"],
  ),
  createPokemon(
    448,
    "lucario",
    "לוקאריו",
    "Lucario",
    "לוחם אמיץ שקורא אאורה, מבין רגשות ומוצא דברים גם ממרחק רב.",
    "A brave fighter that reads aura, understands feelings, and finds things from far away.",
    ["כדור אאורה", "פלאש קנון", "מהירות קיצונית", "קרב צמוד", "דופק עצם", "ריקוד חרבות"],
    ["Aura Sphere", "Flash Cannon", "Extreme Speed", "Close Combat", "Bone Rush", "Swords Dance"],
    ["fighting", "steel"],
    ["riolu", "lucario"],
  ),
  createPokemon(
    656,
    "froakie",
    "פרואקי",
    "Froakie",
    "צפרדע זריזה שמכסה את צווארה בבועות רכות להגנה וקופצת בלי להשמיע קול.",
    "A nimble frog protected by soft bubbles around its neck that jumps without making a sound.",
    ["בועות", "סילון מים", "ליקוק", "מתקפה מהירה", "עשן"],
    ["Bubble", "Water Pulse", "Lick", "Quick Attack", "Smokescreen"],
    ["water"],
    ["froakie", "frogadier", "greninja"],
  ),
  createPokemon(
    657,
    "frogadier",
    "פרוגדיר",
    "Frogadier",
    "אקרובט מים שמטפס על מגדלים גבוהים ויורה בועות בדיוק רב.",
    "A water acrobat that climbs tall towers and launches bubbles with great accuracy.",
    ["פעימת מים", "מתקפה מהירה", "כוכבי מים", "ליקוק", "קפיצה"],
    ["Water Pulse", "Quick Attack", "Water Shuriken", "Lick", "Bounce"],
    ["water"],
    ["froakie", "frogadier", "greninja"],
  ),
  createPokemon(
    658,
    "greninja",
    "גרנינג׳ה",
    "Greninja",
    "נינג׳ת מים מהירה שיוצרת כוכבי מים חדים ונעה בשקט מוחלט.",
    "A swift water ninja that creates sharp water stars and moves in complete silence.",
    ["שוריקן מים", "פעימת חושך", "הידרו פאמפ", "אקרובטיקה", "התקפה נסתרת", "קרן קרח"],
    ["Water Shuriken", "Dark Pulse", "Hydro Pump", "Acrobatics", "Night Slash", "Ice Beam"],
    ["water", "dark"],
    ["froakie", "frogadier", "greninja"],
  ),
  createPokemon(
    722,
    "rowlet",
    "ראולט",
    "Rowlet",
    "ינשוף עגול ושקט שאוסף אור ביום ויורה נוצות חדות ומדויקות.",
    "A round, quiet owl that gathers light by day and fires sharp, accurate feathers.",
    ["עלה תער", "ניקור", "הפתעה", "סינתזה", "רוח עלים"],
    ["Razor Leaf", "Peck", "Astonish", "Synthesis", "Leafage"],
    ["grass", "flying"],
    ["rowlet", "dartrix", "decidueye"],
  ),
  createPokemon(
    723,
    "dartrix",
    "דארטריקס",
    "Dartrix",
    "ינשוף אלגנטי שמטפח את נוצותיו וזורק אותן כמו חצים אל המטרה.",
    "An elegant owl that carefully grooms its feathers and throws them like arrows.",
    ["עלה תער", "מריטת נוצות", "סינתזה", "הפתעה", "ריקוד נוצות"],
    ["Razor Leaf", "Pluck", "Synthesis", "Astonish", "Feather Dance"],
    ["grass", "flying"],
    ["rowlet", "dartrix", "decidueye"],
  ),
  createPokemon(
    724,
    "decidueye",
    "דסידואיי",
    "Decidueye",
    "קשת יער שקט שמסוגל לירות נוצת־חץ ולפגוע במטרה רחוקה מאוד.",
    "A silent forest archer that can fire a feather arrow at a very distant target.",
    ["אזיק רוח", "להב עלה", "חץ רוח", "כדור צל", "ציפור אמיצה", "סינתזה"],
    ["Spirit Shackle", "Leaf Blade", "Shadow Sneak", "Shadow Ball", "Brave Bird", "Synthesis"],
    ["grass", "ghost"],
    ["rowlet", "dartrix", "decidueye"],
  ),
  createPokemon(
    725,
    "litten",
    "ליטן",
    "Litten",
    "חתלתול אש שמנקה את פרוותו בקפידה ואוסף בה חום ליצירת כדורי אש.",
    "A fire kitten that carefully cleans its fur and stores heat in it to create fireballs.",
    ["גחלת", "שריטה", "ליקוק", "ניב אש", "נהמה"],
    ["Ember", "Scratch", "Lick", "Fire Fang", "Growl"],
    ["fire"],
    ["litten", "torracat", "incineroar"],
  ),
  createPokemon(
    726,
    "torracat",
    "טוראקאט",
    "Torracat",
    "הפעמון הלוהט על צווארו מצלצל כשהוא מתרגש ומפיק להבות חזקות.",
    "The fiery bell on its neck rings when it gets excited and produces powerful flames.",
    ["ניב אש", "נשיכה", "להבה", "שריטות זעם", "נהמה"],
    ["Fire Fang", "Bite", "Flame Charge", "Fury Swipes", "Roar"],
    ["fire"],
    ["litten", "torracat", "incineroar"],
  ),
  createPokemon(
    727,
    "incineroar",
    "אינסינרואר",
    "Incineroar",
    "מתאבק אש צבעוני שמעמיד פנים שהוא קשוח, אבל עוזר בשמחה לילדים ולחברים.",
    "A flashy fire wrestler that acts tough but happily helps children and friends.",
    ["לאסו אפל", "הסתערות אש", "קרב צמוד", "נשיכת מחץ", "אגרוף אש", "הפחדה"],
    ["Darkest Lariat", "Flare Blitz", "Close Combat", "Crunch", "Fire Punch", "Scary Face"],
    ["fire", "dark"],
    ["litten", "torracat", "incineroar"],
  ),
  createPokemon(
    778,
    "mimikyu",
    "מימיקיו",
    "Mimikyu",
    "פוקימון ביישן שלובש תחפושת דמוית פיקאצ׳ו כי הוא מאוד רוצה למצוא חברים.",
    "A shy Pokémon that wears a Pikachu-like costume because it really wants to make friends.",
    ["משחק קשוח", "טופר צל", "צל מתגנב", "קסם", "חרב ריקוד", "חיבוק"],
    ["Play Rough", "Shadow Claw", "Shadow Sneak", "Charm", "Swords Dance", "Mimic"],
    ["ghost", "fairy"],
    ["mimikyu"],
  ),
  createPokemon(
    810,
    "grookey",
    "גרוקי",
    "Grookey",
    "קוף קטן וקצבי שמכה במקל שלו ומחזיר אנרגיה לצמחים סביבו.",
    "A rhythmic little monkey whose stick beats can restore energy to nearby plants.",
    ["ענף דוקר", "שריטה", "פעימת ענף", "התגרות", "צמיחה"],
    ["Branch Poke", "Scratch", "Razor Leaf", "Taunt", "Growth"],
    ["grass"],
    ["grookey", "thwackey", "rillaboom"],
  ),
  createPokemon(
    811,
    "thwackey",
    "ת׳וואקי",
    "Thwackey",
    "מתופף יער שמתאמן עם שני מקלות ושומר תמיד על קצב מדויק.",
    "A forest drummer that practices with two sticks and always keeps a perfect beat.",
    ["להב כפול", "צרור עלים", "התגרות", "מכת ענף", "הטחה"],
    ["Double Hit", "Razor Leaf", "Taunt", "Branch Poke", "Slam"],
    ["grass"],
    ["grookey", "thwackey", "rillaboom"],
  ),
  createPokemon(
    812,
    "rillaboom",
    "רילאבום",
    "Rillaboom",
    "מתופף עוצמתי שמכוון שורשים וצמחים בעזרת המקצבים של התוף הגדול שלו.",
    "A powerful drummer that guides roots and plants with rhythms from its giant drum.",
    ["תיפוף תופים", "פטיש עץ", "נוק־אאוט", "רעידת אדמה", "להב תער", "בום קולי"],
    ["Drum Beating", "Wood Hammer", "Knock Off", "Earthquake", "Razor Leaf", "Boomburst"],
    ["grass"],
    ["grookey", "thwackey", "rillaboom"],
  ),
  createPokemon(
    813,
    "scorbunny",
    "סקורבאני",
    "Scorbunny",
    "ארנב אש מלא מרץ שרץ בלי הפסקה עד שכפות רגליו מתחממות וזוהרות.",
    "An energetic fire rabbit that runs nonstop until the pads of its feet grow hot and glow.",
    ["גחלת", "בעיטה כפולה", "מתקפה מהירה", "להבה", "זריזות"],
    ["Ember", "Double Kick", "Quick Attack", "Flame Charge", "Agility"],
    ["fire"],
    ["scorbunny", "raboot", "cinderace"],
  ),
  createPokemon(
    814,
    "raboot",
    "ראבוט",
    "Raboot",
    "שחקן מהיר שמתאמן בבעיטות ושומר את ידיו בפרווה החמה כדי להתרכז.",
    "A speedy player that practices kicks and keeps its hands in warm fur to stay focused.",
    ["בעיטה לוהטת", "מתקפה מהירה", "להבה", "הסתערות ראש", "זריזות"],
    ["Flame Charge", "Quick Attack", "Ember", "Headbutt", "Agility"],
    ["fire"],
    ["scorbunny", "raboot", "cinderace"],
  ),
  createPokemon(
    815,
    "cinderace",
    "סינדרייס",
    "Cinderace",
    "כוכב כדורגל לוהט שבועט חלוקי אבן כמו כדורי אש מהירים ומדויקים.",
    "A fiery football star that kicks pebbles like fast, accurate fireballs.",
    ["כדור אש", "בעיטה גבוהה", "להבה", "מתקפה מהירה", "שינוי צד", "ראש ברזל"],
    ["Pyro Ball", "High Jump Kick", "Flame Charge", "Quick Attack", "Court Change", "Iron Head"],
    ["fire"],
    ["scorbunny", "raboot", "cinderace"],
  ),
];
